---
- hosts: "{{ lookup('env', 'SERVER_IP') }}"
  tasks:
    - name: update apt repo
      action: apt update-cache=yes

    - name: install nginx 
      action: apt name=nginx state=installed
      
    - name: remove default host file
      file: path=/etc/nginx/sites-enabled/default state=absent
      
    - name: firewall - allow ssh
      ufw: rule=allow name=OpenSSH
      
    - name: firewall - allow HTTP
      ufw: rule=allow port=80 proto=tcp
      
    - name: firewall - allow HTTPS
      ufw: rule=allow port=443 proto=tcp
      
    - name: firewall - let mosh pass
      ufw: rule=allow port=60000:61000 proto=udp      
      
    - name: firewall - enable
      ufw: state=enabled policy=reject
      
    - name: install various packages 
      apt: name={{item}} state=installed
      with_items:
            - vim
            - curl
            - wget
            - unzip
            - tmux
            - mosh
            - haveged      
      

