---
- hosts: "{{ lookup('env', 'DEV_MACHINE') }}"
  gather_facts: False 
  tasks: 
    - name: apt-get update 
      raw: apt-get update -qq 
    - name: Install python 2.7 
      raw: apt-get install -qq python2.7
