---
- hosts: "{{ lookup('env', 'DEV_MACHINE') }}"
  roles:
    - williamyeh.oracle-java
  tasks:
    - name: remove wrong java link 
      file: path=/usr/lib/jvm/default-java state=absent

    - name: set right java link 
      file: 
        src: /usr/lib/jvm/jdk1.8.0_102
        dest: /usr/lib/jvm/default-java 
        state: link
     
    - name: install maven
      action: apt name=maven state=installed
    
    - name: install ant
      action: apt name=ant state=installed
      
    - name: install gradle
      action: apt name=gradle state=installed          
      
  vars:
    java_version: 8
    java_subversion: 102
    java_set_javahome: true
