---
- hosts: "{{ lookup('env', 'DEV_MACHINE') }}"
  roles:
     - { role: cmprescott.chrome, become: yes }
  tasks:
    - name: install packages 
      apt: name={{item}} state=installed
      with_items:
            - git
            - vim
            - curl
            - wget
            - unzip
            - openvpn
            - python-pip
            - zsh
            - tmux
            - mosh
            - nginx
            - ruby-full
            - tcpflow
            - httpry
            - haveged
            
    - name: make sure nginx is stopped
      action: service name=nginx state=stopped            

    - name: install python virtualenv
      raw: pip install virtualenv