---
- hosts: "{{ lookup('env', 'DEV_MACHINE') }}"
  tasks:
    - name: install packages 
      apt: name={{item}} state=installed
      with_items:
            - git
            - vim
            - curl
            - wget
            - unzip
            - openvpn
            - python-pip
            - zsh
            - tmux
            - mosh
