---
- hosts: "{{ lookup('env', 'DEV_MACHINE') }}"
  tasks:      
    - name: create developer
      user: name=developer generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
      
    - name: developer groups
      user: name=developer groups=developer,docker,sudo
            
    - name: remove bashrc
      file: path=/home/developer/.bashrc state=absent
      
    - name: remove profile
      file: path=/home/developer/.profile state=absent
      
    - name: clone dotfiles
      git: repo=https://github.com/fdiotalevi/dotfiles.git dest=/tmp/dotfiles
      become: yes
      become_user: developer
      
    - name: remove .git folder
      file: path=/tmp/dotfiles/.git state=absent
        
    - name: copy dotfiles
      raw: cp -r /tmp/dotfiles/. /home/developer
      become: yes
      become_user: developer
      
    - name: remove tmp dotfiles folder
      file: path=/tmp/dotfiles state=absent      
